" .vimrc
" Generated by Gemini CLI

" --- Plugin Manager (vim-plug) ---
" Install vim-plug if not found
if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

call plug#begin('~/.vim/plugged')

" Colorscheme
Plug 'catppuccin/vim', { 'as': 'catppuccin' }

" Fuzzy Finder
Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
Plug 'junegunn/fzf.vim'

" LSP & Autocomplete
Plug 'prabirshrestha/vim-lsp'
Plug 'mattn/vim-lsp-settings'
Plug 'prabirshrestha/asyncomplete.vim'
Plug 'prabirshrestha/asyncomplete-lsp.vim'

call plug#end()

" --- Generic Config ---
set number
set relativenumber
set expandtab
set tabstop=2
set shiftwidth=2
set smartindent
set clipboard^=unnamedplus " Clipboard support
set termguicolors
set updatetime=200
set cursorline
set ignorecase
set smartcase
set signcolumn=yes
set noswapfile
set undofile
set hidden

" --- Colorscheme & Highlight Settings ---
" Set catppuccin flavor
let g:catppuccin_flavour = "macchiato" 

" Apply customizations on ColorScheme event to ensure they override defaults
augroup CustomHighlights
  autocmd!
  autocmd ColorScheme * call s:apply_custom_highlights()
augroup END

function! s:apply_custom_highlights()
  " Transparent Background
  highlight Normal guibg=NONE ctermbg=NONE
  highlight NonText guibg=NONE ctermbg=NONE
  highlight LineNr guibg=NONE ctermbg=NONE
  highlight SignColumn guibg=NONE ctermbg=NONE
  highlight EndOfBuffer guibg=NONE ctermbg=NONE
  
  " CursorLine & Menu
  highlight CursorLine guibg=#2a273f
  highlight Pmenu guibg=#232136 guifg=#e0def4
  highlight PmenuSel guibg=#ea9a97 guifg=#232136
  
  " LSP Inlay Hint - Force explicit color (Very muted gray/purple)
  " Using ! to force overwrite any existing links
  highlight! LspInlayHint guifg=#5b6078 guibg=NONE gui=italic
  
  " Remove LSP Diagnostic backgrounds
  highlight LspErrorHighlight guibg=NONE ctermbg=NONE gui=undercurl guisp=Red
  highlight LspWarningHighlight guibg=NONE ctermbg=NONE gui=undercurl guisp=Yellow
  highlight LspInformationHighlight guibg=NONE ctermbg=NONE gui=undercurl guisp=Blue
  highlight LspHintHighlight guibg=NONE ctermbg=NONE gui=undercurl guisp=Green
  
  " Remove Sign backgrounds
  highlight LspErrorText guibg=NONE guifg=Red
  highlight LspWarningText guibg=NONE guifg=Yellow
  highlight LspInformationText guibg=NONE guifg=Blue
  highlight LspHintText guibg=NONE guifg=Green
endfunction

try
  colorscheme catppuccin_macchiato
catch /^Vim\%((\a\+)\)\=:E185/
  " Fallback if color scheme not installed
  colorscheme default
endtry

" Manually trigger the function once for startup
call s:apply_custom_highlights()


" --- Keymaps ---
let mapleader = " "

" Fuzzy Finder (FZF)
nnoremap <Leader>f :Files<CR>
nnoremap <Leader>/ :Rg<CR>
nnoremap <Leader>b :Buffers<CR>

" FZF Ignore target and .git
let $FZF_DEFAULT_COMMAND = 'rg --files --hidden --smart-case --glob "!.git/*" --glob "!target/*"'
command! -bang -nargs=? -complete=dir Files
  \ call fzf#vim#files(<q-args>, fzf#vim#with_preview(), <bang>0)

" LSP Configuration
function! s:on_lsp_buffer_enabled() abort
    setlocal omnifunc=lsp#complete
    setlocal signcolumn=yes
    if exists('+tagfunc') | setlocal tagfunc=lsp#tagfunc | endif
    
    " LSP Mappings
    nmap <buffer> gd <plug>(lsp-definition)
    nmap <buffer> gr <plug>(lsp-references)
    nmap <buffer> K <plug>(lsp-hover)
    nmap <buffer> <leader>r <plug>(lsp-rename)
    nmap <buffer> <leader>ca <plug>(lsp-code-action)
    nmap <buffer> <leader>e <plug>(lsp-document-diagnostics)
    nmap <buffer> <leader>s :LspDocumentSymbol<CR>
    nmap <buffer> [d <plug>(lsp-previous-diagnostic)
    nmap <buffer> ]d <plug>(lsp-next-diagnostic)

    " Format on save
    " autocmd BufWritePre <buffer> LspDocumentFormatSync
endfunction

augroup lsp_install
    au!
    autocmd User lsp_buffer_enabled call s:on_lsp_buffer_enabled()
augroup END

" LSP Settings (vim-lsp-settings)
let g:lsp_settings = {
\  'rust-analyzer': {
\    'workspace_config': {
\      'rust-analyzer': {
\        'checkOnSave': {'command': 'clippy'},
\        'inlayHints': {
\           'enable': v:true,
\           'typeHints': v:true,
\           'parameterHints': v:true,
\           'chainingHints': v:true,
\        }
\      }
\    }
\  },
\}

" Enable Inlay Hints (Global)
let g:lsp_inlay_hints_enabled = 1

" LSP Symbols Picker using FZF if available
command! -bang -nargs=* LspSymbols
  \ call fzf#vim#grep(
  \   'grep --column --line-number --no-heading --color=always --smart-case '.shellescape(<q-args>), 1,
  \   fzf#vim#with_preview(), <bang>0)

" Enable diagnostics
let g:lsp_diagnostics_enabled = 1
let g:lsp_diagnostics_echo_cursor = 1

" --- Autocomplete Config (asyncomplete) ---
inoremap <expr> <Tab>   pumvisible() ? "\<C-n>" : "\<Tab>"
inoremap <expr> <S-Tab> pumvisible() ? "\<C-p>" : "\<S-Tab>"
inoremap <expr> <cr>    pumvisible() ? "\<C-y>" : "\<cr>"
inoremap <silent><expr> <C-Space> asyncomplete#force_refresh()