# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "nvme"
    "xhci_pci"
    "usb_storage"
    "usbhid"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/mapper/luks-5c4ff8a1-c35d-4244-8a36-f81bc112f164";
    fsType = "ext4";
  };

  boot.initrd.luks.devices."luks-5c4ff8a1-c35d-4244-8a36-f81bc112f164".device =
    "/dev/disk/by-uuid/5c4ff8a1-c35d-4244-8a36-f81bc112f164";

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/3810-C777";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  swapDevices = [
    { device = "/dev/mapper/luks-82faf233-904a-4f35-8b07-47c8b1cad332"; }
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
