# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "nvme"
    "xhci_pci"
    "usb_storage"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/mapper/luks-1caafebc-0f3c-4a68-97b9-db3c107faf0b";
    fsType = "ext4";
  };

  boot.initrd.luks.devices."luks-1caafebc-0f3c-4a68-97b9-db3c107faf0b".device =
    "/dev/disk/by-uuid/1caafebc-0f3c-4a68-97b9-db3c107faf0b";

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/FA8F-0CF6";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  swapDevices = [
    { device = "/dev/mapper/luks-1dc20a4c-0384-4870-bb99-e5a65f1df495"; }
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
