[main]
font="0xProto Nerd Font:size=12"
width=40
lines=40
prompt="󰍉 "
horizontal-pad=20
vertical-pad=15
inner-pad=10
dpi-aware=no
border-radius=15
border-width=2

[colors]
background=181825cc
text=cdd6f4ff
match=f5c2e7ff
selection=313244cc
selection-text=cdd6f4ff
selection-match=f5c2e7ff
border=cba6f7ff
;
