[main]
font="0xProto Nerd Font:size=12"
width=50
lines=50
prompt="󰍉 "
horizontal-pad=20
vertical-pad=12
inner-pad=8
dpi-aware=no
border-radius=12
border-width=2
icon-theme=Adwaita
icons-enabled=yes
fields=name,generic,comment,categories,filename
sort=yes

[colors]
background=181825b3
text=cdd6f4ff
match=f5c2e7ff
selection=89b4facc
selection-text=1e1e2eff
selection-match=f5c2e7ff
border=cba6f7dd
;
