" Disable netrw (default file explorer)
let g:loaded_netrw = 1
let g:loaded_netrwPlugin = 1

set relativenumber
set number

set list
set listchars=tab:›\ ,trail:~,nbsp:␣

set wrap
set linebreak
set breakindent
set showbreak=⤷\ 

set clipboard=unnamedplus
set hlsearch

set tabstop=2
set shiftwidth=2
set expandtab

set termguicolors
set updatetime=1000
set cursorline

" set foldtext=
" set foldmethod=expr
" set foldexpr=v:lua.vim.treesitter.foldexpr()
" set foldenable
" set foldlevel=99
" set foldlevelstart=99
" set foldcolumn=auto
"
set mouse=a
set signcolumn=yes
" set colorcolumn=100

set autoread
set nomodeline

syntax on
syntax match DangerousChars /[\u200B\u200C\u200D\uFEFF\u202E\u2066-\u2069]/
highlight DangerousChars ctermbg=red guibg=red

" ---------------------
"  XDG base directory
" ---------------------
let s:config_home = empty($XDG_CONFIG_HOME) ? expand('~/.config') : $XDG_CONFIG_HOME
let s:data_home   = empty($XDG_DATA_HOME)   ? expand('~/.local/share') : $XDG_DATA_HOME

let s:vim_dir     = s:config_home . '/vim'
let s:autoload_dir= s:data_home . '/vim/autoload'
let s:plug_path   = s:autoload_dir . '/plug.vim'

" Ensure runtimepath
execute 'set runtimepath^=' . s:vim_dir

" ---------------------
"  download vim-plug
" ---------------------
if empty(glob(s:plug_path))
    silent execute '!curl -fLo ' . s:plug_path . ' --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
endif

" Source vim-plug
if filereadable(s:plug_path)
    execute 'source ' . s:plug_path
endif

" ---------------------
"  install plugins
" ---------------------
call plug#begin(s:data_home . '/vim/plugged')

" Color scheme
Plug 'rose-pine/vim', { 'as': 'rosepine' }

call plug#end()

set background=dark
colorscheme rosepine_moon
