general {
    lock_cmd = pidof hyprlock || hyprlock       # ロックコマンド
    before_sleep_cmd = loginctl lock-session    # スリープ前にロック
    after_sleep_cmd = niri msg action power-on-monitors # 復帰時にモニターをオン
}

listener {
    timeout = 1800
    on-timeout = loginctl lock-session
}
