#!/usr/bin/env sh

yabai -m config layout bsp
yabai -m config top_padding 8
yabai -m config bottom_padding 8
yabai -m config left_padding 8
yabai -m config right_padding 8
yabai -m config window_gap 8
yabai -m config auto_balance on
yabai -m config mouse_follows_focus off
yabai -m config focus_follows_mouse autoraise

# Reserved labels used by skhd scratchpad/message approximations
yabai -m space 9 --label msg
yabai -m space 10 --label scrpad
