general {
    gaps_in = 2
    gaps_out = 4

    border_size = 2

    layout = dwindle
}

decoration {
    rounding = 12

    blur {
        enabled = true
        size = 5
        passes = 3
        new_optimizations = true
        ignore_opacity = true
        xray = false
    }

    shadow {
        enabled = false
    }

    dim_inactive = true
    dim_strength = 0.15
}

animations {
    enabled = true

    # カスタムベジェ曲線の定義
    bezier = overshot, 0.05, 0.9, 0.1, 1.1
    bezier = smoothOut, 0.36, 0, 0.66, -0.56
    bezier = smoothIn, 0.25, 1, 0.5, 1
    bezier = cubic, 0.15, 0.85, 0.35, 1.1

    # アニメーションの割り当て
    animation = windows, 1, 6, overshot, slide
    animation = windowsOut, 1, 6, smoothOut, slide
    animation = windowsMove, 1, 6, smoothIn, slide

    animation = border, 1, 10, default
    animation = borderangle, 1, 100, linear, loop
    animation = fade, 1, 5, smoothIn
    animation = workspaces, 1, 7, overshot, slidefade 20%

    animation = specialWorkspace, 1, 6, cubic, slidevert
}
