general {
    disable_loading_bar = true
    hide_cursor = true
}

background {
    monitor =
    path = screenshot
    blur_passes = 3 # 0 disables blurring
    blur_size = 7
    noise = 0.0117
    contrast = 0.8916
    brightness = 0.8172
    vibrancy = 0.1696
    vibrancy_darkness = 0.0
}

input-field {
    monitor =
    size = 250, 50
    outline_thickness = 3
    dots_size = 0.2 # Scale of input-field height, 0.2 - 0.8
    dots_spacing = 0.15 # Scale of dots' absolute size, 0.0 - 1.0
    dots_center = true
    dots_rounding = -1 # -1 default circle, -2 follow input-field rounding
    outer_color = rgba(245, 194, 231, 0.6) # Pink
    inner_color = rgba(24, 24, 37, 0.4) # Base transparent
    font_color = rgb(205, 214, 244) # Lavender
    fade_on_empty = false
    fade_timeout = 1000 # Milliseconds before fade_on_empty is triggered.
    placeholder_text = <i>Input Password...</i> # Text rendered in the input box when it's empty.
    hide_input = false
    rounding = 10 # -1 means complete rounding (circle/oval)
    check_color = rgba(166, 227, 161, 0.6) # Green
    fail_color = rgba(243, 139, 168, 0.6) # Red
    fail_text = <i>$FAIL <b>($ATTEMPTS)</b></i> # can be set to empty
    fail_transition = 300 # transition time in ms between normal outer_color and fail_color
    capslock_color = rgba(250, 179, 135, 0.6) # Peach
    numlock_color = -1
    bothlock_color = -1 # when both locks are active. -1 means don't change outer color (same for above)
    invert_numlock = false # change color if numlock is off
    swap_font_color = false # see below

    position = 0, -120
    halign = center
    valign = center
}

label {
    monitor =
    # Time
    text = $TIME
    color = rgb(203, 166, 247) # Mauve
    font_size = 120
    font_family = 0xProto Nerd Font Mono ExtraBold
    position = 0, 160
    halign = center
    valign = center
    shadow_passes = 2
}

label {
    monitor =
    # Date
    text = cmd[update:43200000] echo "$(date +"%A, %d %B %Y")"
    color = rgb(205, 214, 244) # Lavender
    font_size = 24
    font_family = 0xProto Nerd Font
    position = 0, 50
    halign = center
    valign = center
    shadow_passes = 1
}

label {
    monitor =
    text = Welcome back, $USER
    color = rgb(245, 194, 231) # Pink
    font_size = 18
    font_family = 0xProto Nerd Font
    position = 0, -70
    halign = center
    valign = center
}

auth {
    fingerprint:enabled = true
    fingerprint:ready_message = <span foreground="##a6e3a1">(scan fingerprint)</span>
    fingerprint:present_message = <span foreground="##89b4fa">authenticating...</span>
    fingerprint:failed_message = <span foreground="##f38ba8">authentication failed</span>
}
