general {
    gaps_in = 2
    gaps_out = 7

    border_size = 2

    layout = dwindle

    col.active_border   = rgba(89b4faaa)
    col.inactive_border = rgba(ffffff18)

    resize_on_border = false

    allow_tearing = false
}

decoration {
    rounding = 12

    active_opacity = 1.0
    inactive_opacity = 1.0

    shadow {
        enabled = false
    }

    blur {
        enabled = false
    }

    dim_inactive = false
    dim_strength = 0.15
}

animations {
    enabled = true

    bezier = myBezier, 0.05, 0.9, 0.1, 1.0
    bezier = overshot, 0.05, 0.9, 0.1, 1.02
    bezier = cubic, 0.2, 1, 0, 1
    bezier = linear, 0, 0, 1, 1

    animation = windows, 1, 5, overshot, slide
    animation = windowsIn, 1, 5, overshot, slide
    animation = windowsOut, 1, 5, cubic, slide
    animation = windowsMove, 1, 5, myBezier

    animation = workspaces, 1, 4, cubic, fade
    animation = specialWorkspace, 1, 6, cubic, slidevert
}

