[mgr]
radio = [3, 3, 4]
sort_by = "mtime"
linemode = "size"
show_hidden = false
show_symlink = true
sort_reverse = true
enter = "enter"
sort_dir_first = false

[[manager.prepend_rules]]
name = ".git/"
use = false

[plugin]
prepend_previewers = [{ url = "*.wav", run = "wav-transcribe" }]

[opener]
pdf = [
  { run = 'zathura "$@"', orphan = true, desc = "Zathura" },
  { run = 'flatpak run com.google.Chrome "$@"', orphan = true, desc = "Google Chrome" },
]

[open]
prepend_rules = [{ mime = "application/pdf", use = "pdf" }]
