[mgr]
sort_by = "mtime"
show_hidden = true
show_symlink = true
sort_reverse = true
enter = "enter"
sort_dir_first = false

[[manager.prepend_rules]]
name = ".git/"
use = false

[plugin]
prepend_previewers = [
	{ url = "*.wav", run = "wav-transcribe" },
]
