[mgr]
radio = [3, 3, 4]
sort_by = "mtime"
linemode = "size"
show_hidden = false
show_symlink = true
sort_reverse = true
enter = "enter"
sort_dir_first = false

[[manager.prepend_rules]]
name = ".git/"
use = false

[plugin]
prepend_previewers = [{ url = "*.wav", run = "wav-transcribe" }]

[opener]
pdf = [
  { run = 'zathura "$@"', orphan = true, desc = "Zathura" },
  { run = 'chromium "$@"', orphan = true, desc = "Chromium" },
  { run = 'firefox "$@"', orphan = true, desc = "Firefox" },
]

image = [
  { run = 'loupe "$@"', orphan = true, desc = "loupe" },
  { run = 'chromium "$@"', orphan = true, desc = "Chromium" },
]

html = [
  { run = 'chromium "$@"', orphan = true, desc = "Chromium" },
  { run = 'firefox "$@"', orphan = true, desc = "Firefox" },
]

[open]
prepend_rules = [
  { mime = "application/pdf", use = "pdf" },
  { mime = "image/*", use = "image" },
  { mime = "text/html", use = "html" },
  { url = "*.html", use = "html" },
]
