vim.g.mapleader = " "

vim.keymap.set("n", "<Leader>a", vim.lsp.buf.code_action, { desc = "lsp code action" })
vim.keymap.set("n", "<Leader>r", vim.lsp.buf.rename, { desc = "lsp rename" })
vim.keymap.set("n", "<Leader>n", ":nohlsearch<CR>", { silent = true })
vim.keymap.set("n", "<leader>U", vim.cmd.redo, { desc = "redo" })
vim.keymap.set("n", "<C-b>", "<Nop>", { noremap = true })
vim.keymap.set({ "n", "i", "v", "x", "s" }, "<C-c>", function()
  require("Comment.api").toggle.linewise.current()
end, { desc = "toggle cooment for ", noremap = true })
vim.keymap.set({ "n", "v", "x", "s" }, "<Leader>gc", function()
  require("Comment.api").toggle.linewise.current()
end, { desc = "toggle cooment for ", noremap = true })
vim.keymap.set("n", "eh", ":lua vim.lsp.inlay_hint.enable(true, { bufnr = 0}) <CR>", { desc = "enable lsp inlay hint" })
vim.keymap.set("n", "<Leader>t", ":NvimTreeToggle<CR>", { silent = true, noremap = true })
