theme = "catppuccin_macchiato"

[editor]
line-number = "relative"
#mouse = true
shell = ["zsh", "-c"]
clipboard-provider = "tmux"
true-color = true
rulers = [100, 120]
preview-completion-insert = false

[editor.file-picker]
# hidden = false

[editor.statusline]
center = ["file-type"]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.lsp]
display-inlay-hints = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.auto-save]
after-delay.enable = true
after-delay.timeout = 800

[editor.whitespace.render]
space = "none"
tab = "all"
nbsp = "all"
nnbsp = "all"
newline = "none"

[editor.indent-guides]
render = true
character = "|"
skip-levels = 1

[editor.whitespace.characters]
space = "·"
nbsp = "⍽"
nnbsp = "␣"
tab = "→"
newline = "↵"
tabpad = "·"

[editor.inline-diagnostics]
cursor-line = "hint"

[keys.normal]
C-s = ":w"
C-o = ":open ~/.config/helix/config.toml"
C-r = ":reload"
"0" = "goto_line_start"
"$" = "goto_line_end"
#"gg" = "goto_file_start"
"G" = "goto_file_end"
#"dd" = "delete_line"
"a" = "insert_at_line_end"
"V" = ["goto_line_start", "select_mode", "extend_line_below", ]
p = ":append-output tmux save-buffer -"

[keys.normal.g]
a = "code_action"
g = "goto_file_start"
c = "toggle_comments"

[keys.normal.d]
d = [ "goto_line_start", "kill_to_line_end", "delete_char_backward"]

[keys.select]
y = [":pipe-to tmux load-buffder -", "yank"]

[keys.insert]
C-r = ":reload"
