hl.curve("expo", { type = "bezier", points = { { 0.16, 1.0 }, { 0.3, 1.0 } } })
hl.curve("back", { type = "bezier", points = { { 0.34, 1.56 }, { 0.64, 1.0 } } })
hl.curve("linear", { type = "bezier", points = { { 0, 0 }, { 1.0, 1.0 } } })
hl.curve("snap", { type = "bezier", points = { { 0.19, 1.0 }, { 0.22, 1.0 } } })

hl.animation({ leaf = "windows", enabled = true, speed = 6, bezier = "expo", style = "popin 70%" })
hl.animation({ leaf = "windowsOut", enabled = true, speed = 5, bezier = "snap", style = "popin 80%" })
hl.animation({ leaf = "windowsMove", enabled = true, speed = 4, bezier = "expo" })
hl.animation({ leaf = "border", enabled = true, speed = 8, bezier = "expo" })
hl.animation({ leaf = "fade", enabled = true, speed = 4, bezier = "expo" })
hl.animation({ leaf = "fadeDim", enabled = true, speed = 4, bezier = "expo" })
hl.animation({ leaf = "workspaces", enabled = true, speed = 4, bezier = "expo", style = "slide" })
hl.animation({ leaf = "specialWorkspace", enabled = true, speed = 4, bezier = "expo", style = "slidevert" })
hl.animation({ leaf = "fadeLayers", enabled = true, speed = 4, bezier = "expo" })
