(deftheme rose-pine-moon
  "Rose Pine Moon theme tuned for transparent terminal backgrounds.")

(let ((base "#232136")
      (surface "#2a273f")
      (overlay "#393552")
      (muted "#6e6a86")
      (subtle "#908caa")
      (text "#e0def4")
      (love "#eb6f92")
      (gold "#f6c177")
      (rose "#ea9a97")
      (pine "#9ccfd8")
      (foam "#9ccfd8")
      (iris "#c4a7e7")
      (green "#95b1ac"))
  (custom-theme-set-faces
   'rose-pine-moon
   `(default ((t (:background ,base :foreground ,text))))
   `(cursor ((t (:background ,rose))))
   `(fringe ((t (:background ,base :foreground ,muted))))
   `(vertical-border ((t (:foreground ,overlay))))
   `(minibuffer-prompt ((t (:foreground ,iris :weight bold))))
   `(region ((t (:background ,overlay :foreground ,text))))
   `(secondary-selection ((t (:background ,surface :foreground ,text))))
   `(highlight ((t (:background ,surface))))
   `(hl-line ((t (:background ,surface))))
   `(line-number ((t (:background ,base :foreground ,muted))))
   `(line-number-current-line ((t (:background ,base :foreground ,gold :weight bold))))
   `(mode-line ((t (:background ,overlay :foreground ,text :box nil))))
   `(mode-line-inactive ((t (:background ,surface :foreground ,subtle :box nil))))
   `(header-line ((t (:background ,surface :foreground ,text :box nil))))
   `(isearch ((t (:background ,gold :foreground ,base :weight bold))))
   `(isearch-fail ((t (:background ,love :foreground ,base :weight bold))))
   `(lazy-highlight ((t (:background ,overlay :foreground ,gold))))
   `(match ((t (:background ,overlay :foreground ,foam :weight bold))))
   `(show-paren-match ((t (:background ,overlay :foreground ,gold :weight bold))))
   `(show-paren-mismatch ((t (:background ,love :foreground ,base :weight bold))))
   `(link ((t (:foreground ,foam :underline t))))
   `(shadow ((t (:foreground ,muted))))
   `(error ((t (:foreground ,love :weight bold))))
   `(warning ((t (:foreground ,gold :weight bold))))
   `(success ((t (:foreground ,green :weight bold))))
   `(font-lock-builtin-face ((t (:foreground ,foam))))
   `(font-lock-comment-face ((t (:foreground ,muted :slant italic))))
   `(font-lock-comment-delimiter-face ((t (:foreground ,muted :slant italic))))
   `(font-lock-constant-face ((t (:foreground ,rose))))
   `(font-lock-doc-face ((t (:foreground ,subtle))))
   `(font-lock-function-name-face ((t (:foreground ,pine :weight semi-bold))))
   `(font-lock-keyword-face ((t (:foreground ,iris :weight semi-bold))))
   `(font-lock-negation-char-face ((t (:foreground ,love))))
   `(font-lock-preprocessor-face ((t (:foreground ,gold))))
   `(font-lock-regexp-grouping-backslash ((t (:foreground ,gold))))
   `(font-lock-regexp-grouping-construct ((t (:foreground ,iris))))
   `(font-lock-string-face ((t (:foreground ,gold))))
   `(font-lock-type-face ((t (:foreground ,foam))))
   `(font-lock-variable-name-face ((t (:foreground ,text))))
   `(font-lock-warning-face ((t (:foreground ,love :weight bold))))
   `(completions-first-difference ((t (:foreground ,gold :weight bold))))
   `(vertico-current ((t (:background ,overlay :foreground ,text))))
   `(corfu-default ((t (:background ,surface :foreground ,text))))
   `(corfu-current ((t (:background ,overlay :foreground ,text))))
   `(corfu-bar ((t (:background ,iris))))
   `(flymake-error ((t (:underline (:style wave :color ,love)))))
   `(flymake-warning ((t (:underline (:style wave :color ,gold)))))
   `(flymake-note ((t (:underline (:style wave :color ,foam)))))
   `(diff-hl-insert ((t (:foreground ,green :background ,green))))
   `(diff-hl-delete ((t (:foreground ,love :background ,love))))
   `(diff-hl-change ((t (:foreground ,gold :background ,gold))))
   `(magit-section-heading ((t (:foreground ,iris :weight bold))))
   `(magit-branch-local ((t (:foreground ,foam))))
   `(magit-branch-remote ((t (:foreground ,green))))
   `(magit-diff-added ((t (:foreground ,green))))
   `(magit-diff-removed ((t (:foreground ,love))))
   `(doom-modeline-bar ((t (:background ,iris))))
   `(doom-modeline-buffer-file ((t (:foreground ,text :weight bold))))
   `(doom-modeline-buffer-modified ((t (:foreground ,gold :weight bold))))))

(provide-theme 'rose-pine-moon)
